# fly.toml file generated for tony-ebpf-proxy on 2023-03-20T17:25:02-07:00

app = "tony-ebpf-proxy"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[env]

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"
